### ISSUE TITLE
issue with parameter count

### ISSUE THREAD

**Issue by eigenAyoub** [terra-quantum-public/TQCompressedGPT2#1]
Hey,

I am struggling a bit to understand how the embedding matrix is constructed back from the following factors: 

![Screenshot from 2024-03-21 00-33-24](https://github.com/terra-quantum-public/TQCompressedGPT2/assets/96575992/f349052b-25b8-4853-8130-64d4bfe2c3ad)

1. If I understood right from the proposed decomposition in the paper, B should have a shape [1,4]? Simply put, how do I construct back the "approximate" embedding matrix, from these factors? 

2. Also, it appears that the other paper (https://arxiv.org/abs/2110.08152) do not count the output matrix (the softmax) in the parameter count, (which would technically make the model of size 120M?!). And I noticed in your checkpoint a parameter named `lm_head.weight`, is it the output layer? and if yes, why don't you count it?

Looking forward to you clarifications, and thanks for providing the code!

**Comment by naumnaum** [comment]
Hello @eigenAyoub!

Thank you for reaching out with your questions. I'll try to clarify the process for you:

The original embedding matrix (**emb**) has the shape [**50257, 768]**. We approximate **emb** using a Kronecker product where:

1. **A** has the shape **[50257, 384]**
2. **B** has the shape **[1, 2]**
Thus, the Kronecker product is given by:

> **emb [50257, 768] ≈ kron_prod(A [50257, 384], B [1, 2])**

We further decompose matrix **A** through a second Kronecker decomposition iteration:

1. **A'** has the shape **[50257, 192]**
2. **B'** has the shape **[1, 2]**
And this gives us:

> **A [50257, 384] ≈ kron_prod(A' [50257, 192], B' [1, 2])**

Regarding your second question, yes, **lm_head.weight** corresponds to the output layer, commonly referred to as the softmax layer. We have chosen not to count this in the total parameter count following the precedent set by the Kronecker Decomposition for GPT Compression paper, as they did not include the softmax layer in their parameter count.

To reconstruct the approximate embedding matrix, you would take the Kronecker products of the decomposed matrices as described above. If there are any further details you'd need, please let me know, and I'd be happy to explain further.

Looking forward to your feedback.

**Comment by eigenAyoub** [comment]
great, thanks for your comeback!
